### ISSUE TITLE
Radeon VII - Low hash rate

### ISSUE THREAD

**Issue by solidappconsulting** [zcoinofficial/sgminer#3]
I'm mining XZC with one Radeon VII. I have only been able to get a hash rate of ~2.2Mh/s and from what I've read online I should be getting ~3.3Mh/s or at least that's what others have using Windows.

I've tried changing the settings with no luck. Here's what I use now: ./sgminer --kernel mtp_vega --intensity 22

Is there anything I can do to increase my hash rate?

Thanks

**Comment by djm34** [comment]
you need to use --worksize 64

please report problems of this order rather to discord channel. Issues on github are more reserved for code related problem/bugs

**Comment by solidappconsulting** [comment]
Thank you! That did the trick. I will use discord channel going forward.
