### ISSUE TITLE
GNU/Linux Debian 10 - build error

### ISSUE THREAD

**Issue by blackmennewstyle** [zcoinofficial/sgminer#5]
I'm using GNU/Linux Debian 10 and I'm getting that error during compilation:

```
At top level:
util.c:2452:13: warning: ‘parse_notify_old’ defined but not used [-Wunused-function]
 static bool parse_notify_old(struct pool *pool, json_t *val)
             ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1163: sgminer-util.o] Error 1
make[2]: Leaving directory '/home/ceedii/sgminer'
make[1]: *** [Makefile:2056: all-recursive] Error 1
make[1]: Leaving directory '/home/ceedii/sgminer'
make: *** [Makefile:767: all] Error 2
```

**Comment by djm34** [comment]
Hi, if there is an error, it isn't in this function (as it is a warning), try rerun make to get the origin of the problem

**Comment by blackmennewstyle** [comment]
> Hi, if there is an error, it isn't in this function (as it is a warning), try rerun make to get the origin of the problem

Hi,

I found this error duplicated a couple of time before:
```
util.c:2056:3: error: expected expression before ‘uint32_t’
   uint32_t tip = 0;
   ^~~~~~~~

```

**Comment by djm34** [comment]
try adding #include <stdint.h>

**Comment by blackmennewstyle** [comment]
> try adding #include <stdint.h> somewhere (although it should be already included)

I added it inside util.c and i'm still getting the exact same error sadly.

**Comment by fractalyse** [comment]
I've tried here are errors : 
```c
util.c:1858:4: error: expected expression before ‘uint32_t’
    uint32_t tip=0;
    ^~~~~~~~

util.c:1957:3: error: expected expression before ‘uint32_t’
   uint32_t tip = 0;
   ^~~~~~~~

util.c:2056:3: error: expected expression before ‘uint32_t’
   uint32_t tip = 0;
   ^~~~~~~~
```

Can be solved by adding some '{' '}' in the code : 
Here is a patch to solve the issue
```patch
1857c1857
< 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
---
> 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
1860d1859
< 		}
1957c1956
< 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
---
> 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
1960d1958
< 	}
2057c2055
< 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
---
> 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
2060d2057
< 	}
```

**Comment by fractalyse** [comment]
I've tried here are errors : 
```c
util.c:1858:4: error: expected expression before ‘uint32_t’
    uint32_t tip=0;
    ^~~~~~~~

util.c:1957:3: error: expected expression before ‘uint32_t’
   uint32_t tip = 0;
   ^~~~~~~~

util.c:2056:3: error: expected expression before ‘uint32_t’
   uint32_t tip = 0;
   ^~~~~~~~
```

Can be solved by adding some '{' '}' in the code : 
Here is a patch to solve the issue
```patch
1857c1857
< 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
---
> 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
1859a1860
> 		}
1956c1957
< 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
---
> 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
1958a1960
> 	}
2055c2057
< 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
---
> 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
2057a2060
> 	}

```

**Comment by blackmennewstyle** [comment]
> I've tried here are errors :
> 
> ```c
> util.c:1858:4: error: expected expression before ‘uint32_t’
>     uint32_t tip=0;
>     ^~~~~~~~
> 
> util.c:1957:3: error: expected expression before ‘uint32_t’
>    uint32_t tip = 0;
>    ^~~~~~~~
> 
> util.c:2056:3: error: expected expression before ‘uint32_t’
>    uint32_t tip = 0;
>    ^~~~~~~~
> ```
> 
> Can be solved by adding some '{' '}' in the code :
> Here is a patch to solve the issue
> 
> ```diff
> 1857c1857
> < 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
> ---
> > 		else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
> 1859a1860
> > 		}
> 1956c1957
> < 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
> ---
> > 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
> 1958a1960
> > 	}
> 2055c2057
> < 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize)
> ---
> > 	else if (bos_sizeof(pool->sockbuf) > pool->sockbuf_bossize) {
> 2057a2060
> > 	}
> ```
> 
> @djm34 see https://github.com/zcoinofficial/sgminer/blob/master/doc/coding.md
> 
> Then you will face an error like this one :
> 
> ```
> algorithm/sgminer-qubitcoin.o: In function `qubitcoin_test':
> qubitcoin.c:(.text+0x94): undefined reference to `qhash'
> algorithm/sgminer-qubitcoin.o: In function `qubitcoin_regenhash':
> qubitcoin.c:(.text+0x134): undefined reference to `qhash'
> algorithm/sgminer-qubitcoin.o: In function `scanhash_qubitcoin':
> qubitcoin.c:(.text+0x1e2): undefined reference to `qhash'
> algorithm/sgminer-quarkcoin.o: In function `quarkcoin_test':
> quarkcoin.c:(.text+0x44): undefined reference to `quarkhash'
> algorithm/sgminer-quarkcoin.o: In function `quarkcoin_regenhash':
> quarkcoin.c:(.text+0xe4): undefined reference to `quarkhash'
> algorithm/sgminer-quarkcoin.o: In function `scanhash_quarkcoin':
> quarkcoin.c:(.text+0x192): undefined reference to `quarkhash'
> algorithm/sgminer-animecoin.o: In function `animecoin_test':
> animecoin.c:(.text+0x44): undefined reference to `animehash'
> algorithm/sgminer-animecoin.o: In function `animecoin_regenhash':
> animecoin.c:(.text+0xe4): undefined reference to `animehash'
> algorithm/sgminer-animecoin.o: In function `scanhash_animecoin':
> animecoin.c:(.text+0x192): undefined reference to `animehash'
> algorithm/sgminer-sifcoin.o: In function `sifcoin_test':
> sifcoin.c:(.text+0x44): undefined reference to `sifhash'
> algorithm/sgminer-sifcoin.o: In function `sifcoin_regenhash':
> sifcoin.c:(.text+0xe4): undefined reference to `sifhash'
> algorithm/sgminer-sifcoin.o: In function `scanhash_sifcoin':
> sifcoin.c:(.text+0x192): undefined reference to `sifhash'
> algorithm/sgminer-twecoin.o: In function `twecoin_test':
> twecoin.c:(.text+0x44): undefined reference to `twehash'
> algorithm/sgminer-twecoin.o: In function `twecoin_regenhash':
> twecoin.c:(.text+0xe4): undefined reference to `twehash'
> algorithm/sgminer-twecoin.o: In function `scanhash_twecoin':
> twecoin.c:(.text+0x192): undefined reference to `twehash'
> algorithm/sgminer-marucoin.o: In function `marucoin_test':
> marucoin.c:(.text+0xf4): undefined reference to `maruhash'
> algorithm/sgminer-marucoin.o: In function `marucoin_regenhash':
> marucoin.c:(.text+0x194): undefined reference to `maruhash'
> algorithm/sgminer-marucoin.o: In function `scanhash_marucoin':
> marucoin.c:(.text+0x242): undefined reference to `maruhash'
> algorithm/sgminer-talkcoin.o: In function `talkcoin_test':
> talkcoin.c:(.text+0x94): undefined reference to `talkhash'
> ...
> ```
> 
> The easiest way is to use sed to remove the 'inline' in function declaration
> 
> ```shell
> sed -i 's/^inline //g' algorithm/*
> ```
> 
> Then clean the repo and rebuild
> 
> ```shell
> make clean
> make
> ```
> 
> and voilà

Thank you so much. It worked out perfectly :+1: 
Compilation successful :)
